### PR TITLE
Prevent loading association when include_data is set to false

### LINKED ISSUE #1707: Bug: include_data loads association
#### Expected behavior vs actual behavior

Given the following serializer:

```ruby
class PostSerializer < ActiveModel::Serializer
  has_many :comments do
    link :related do
      href "/posts/#{object.id}/comments"
    end
    include_data false
  end
end
```

This correctly does not include comment relationship data in the response. However, all the comments are still loaded (ie `select * from comments where post_id = ?`). I would expect this to avoid loading the comments since none of that data is needed in the response.

#### Steps to reproduce

Any serializer with `include_data false`, look at the ActiveRecord queries that fire.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: master/0165215

Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

OS Type & Version: OSX 10.10.5 (Yosemite)

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails 5 beta 3

### PR DESCRIPTION
**Pull request by groyoh**
#### Purpose
Fixes #1707. 

#### Changes
Do not call `read_attribute_for_serialization` when `include_data` is set to `false`.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
gasp! those errors!
didyou/can you rebase? I *think* some jruby fixes were merged recently

**Comment by groyoh** [comment]
Yeah, already rebased to latest master. Not sure what happens here, I can't reproduce it locally.

**Comment by NullVoxPopuli** [comment]
what if you uninstall the sqlite3 adapter? - it's complaining that it's not installed. 

While it's not a dep of ams, it is for the [ActiveRecord tests](https://github.com/rails-api/active_model_serializers/blob/b73b780b7961b7708a40aefd016bb543a4e8137c/test/fixtures/active_record.rb#L3)

**Comment by groyoh** [comment]
I don't have sqlite3 adapter installed locally.

**Comment by NullVoxPopuli** [comment]
even weirder

**Comment by groyoh** [comment]
Actually, sqlite3 adapter comes out of the box with AR. So THAT's even weirder.

File: lib/active_model/serializer/reflection.rb [hunk 1]
```diff
@@ -75,10 +75,10 @@ def value(serializer)
 
         if block
           block_value = instance_exec(serializer, &block)
-          if block_value == :nil
-            serializer.read_attribute_for_serialization(name)
-          else
+          if block_value != :nil
             block_value
+          elsif @_include_data
```
Comment (NullVoxPopuli) [inline lib/active_model/serializer/reflection.rb]: when is `@_include_data` present?

Comment (groyoh) [inline lib/active_model/serializer/reflection.rb]: I'm not sure about the question but it is set to `true` by default so includes the relationship `data` by default. The point of the PR is to prevent calling the relationship if `include_data` is set to `false`.

Comment (NullVoxPopuli) [inline lib/active_model/serializer/reflection.rb]: aight, I guess we'll document _include_data at a later date

**Comment by NullVoxPopuli** [comment]
woo! LGTM :pizza:

**Comment by NullVoxPopuli** [comment]
@groyoh do you want to add a changelog entry?

**Comment by groyoh** [comment]
@NullVoxPopuli will do.

File: lib/active_model/serializer/reflection.rb (hunk 1 above)
Comment (groyoh) [inline lib/active_model/serializer/reflection.rb]: It's already documented but the behavior added in this PR is not though.

**Comment by groyoh** [comment]
@NullVoxPopuli added the CHANGELOG.

**Comment by NullVoxPopuli** [comment]
thanks! merging!

**Comment by YoranBrondsema** [comment]
Although small, this PR has a very big impact for the performance of our app. Would it be possible to bump the version so that the latest version includes this? Thanks!

**Comment by NullVoxPopuli** [comment]
you can specify a commit hash in your gemfile. :-)

we aren't ready to bump the version quite yet.

**Comment by YoranBrondsema** [comment]
I know that :-). I was just wondering if a patch update was possible so that everyone can benefit from this change now, but I will resort to specifying the commit.

**Comment by sandstrom** [comment]
This is a great addition, but wouldn't it make more sense if this was an option:

```ruby
has_one :blog, :include_data => false do |serializer|
  serializer.cached_blog
end
```

Instead of being set from within the block? Or have I missed something?

File: test/adapter/json_api/relationships_test.rb [hunk 2]
```diff
@@ -158,10 +157,16 @@ def test_relationship_meta
           end
 
           def test_relationship_not_including_data
+            @author.define_singleton_method(:read_attribute_for_serialization) do |attr|
+              fail 'should not be called' if attr == :blog
```
Comment (bf4) [inline test/adapter/json_api/relationships_test.rb]: this test needs to change as well.  It shouldn't be raising a runtime error  and is hard to read and why do we even need the define_singleton_method?

😦

File: lib/active_model/serializer/reflection.rb (hunk 1 above)
Comment (bf4) [inline lib/active_model/serializer/reflection.rb]: @NullVoxPopuli please don't merge code with missing `else` clauses.  I was going to say it was a bug and raise a ❗ but then I realized that it was the feature of the PR. 😱   :(

File: test/adapter/json_api/relationships_test.rb (hunk 2 above)
Comment (bf4) [inline test/adapter/json_api/relationships_test.rb]: I also don't understand why this test was changed

Comment (bf4) [inline test/adapter/json_api/relationships_test.rb]: In any case, this test file is basically garbage. See  https://github.com/rails-api/active_model_serializers/pull/1857 would be better to do an 'integration' test

File: lib/active_model/serializer/reflection.rb (hunk 1 above)
Comment (NullVoxPopuli) [inline lib/active_model/serializer/reflection.rb]: makes sense.
