### PR TITLE
Fix duplicate resources inside included in compound document.

### LINKED ISSUE #1202: Duplicate resource object in compound document
There's a bug here (unless I'm reading something wrong) and I can't find an open issue that describes this. Please forgive me if this is a duplicate.

**Reproduction set-up**

Making a [compound document](http://jsonapi.org/format/#document-compound-documents) using `include`. It contains an `Organization`, which `has_many :people`, and `Person` `belongs_to :organization` (there are many other cases that would reproduce this, I think). I have an organization with ID 1, and some people belonging to that organization. The document would have an array of people in the `included` key.

**The bug**

The JSON API spec says:

> A compound document MUST NOT include more than one resource object for each type and id pair.

The `compound document` consists of a document containing both `data` and `included` top-level keys. The `data` is just the `Organization` with ID 1, which has `relationships` which has `people` which has `data`, which is an array of `Person` objects with just `type` (==`people`) and `id`.

In the `included` top-level key, you have the `Person` entities related to the organization. But also, the `Organization` appears here. So you have two resource objects in the same compound document with the same type (`organization`) and ID (`1`). That's a bug, right?

### PR DESCRIPTION
**Pull request by beauby**
This fixes #1202.

### CODE REVIEW

**Comment by beauby** [comment]
@hut8 Could you test this patch?

**Comment by hut8** [comment]
@beauby The test LGTM. It does appear to stop producing the duplicate I saw in the original issue. Thanks!

**Comment by NullVoxPopuli** [comment]
Thanks for verifying @hut8.

@beauby this looks good to me.

File: lib/active_model/serializer/adapter/json_api.rb [hunk 1]
```diff
@@ -84,13 +84,15 @@ def serializable_hash_for_collection(options)
...
             result = self.class.new(s, instance_options.merge(fieldset: fieldset)).serializable_hash(options)
             hash[:data] << result[:data]
+            next unless result[:included]
 
-            if result[:included]
-              hash[:included] ||= []
-              hash[:included] |= result[:included]
-            end
+            hash[:included] ||= []
+            hash[:included] |= result[:included]
```
Comment (NullVoxPopuli) [inline lib/active_model/serializer/adapter/json_api.rb]: why bitwise `or` here?

File: lib/active_model/serializer/adapter/json_api.rb [hunk 2]
```diff
@@ -84,13 +84,15 @@ def serializable_hash_for_collection(options)
...
           end
 
+          hash[:included].delete_if { |resource| Array(hash[:data]).include?(resource) } if hash[:included]
+          hash.delete(:included) if hash[:included] && hash[:included].empty?
```
Comment (NullVoxPopuli) [inline lib/active_model/serializer/adapter/json_api.rb]: can these two lines be extracted to a method?

File: test/adapter/json_api/linked_test.rb [hunk 3]
```diff
@@ -277,6 +277,79 @@ def test_nil_link_with_specified_serializer
...
           end
         end
+
+        class NoDuplicatesTest < Minitest::Test
+          Post = Class.new(::Model)
+          Author = Class.new(::Model)
+
+          class PostSerializer < ActiveModel::Serializer
+            type 'posts'
+            class AuthorSerializer < ActiveModel::Serializer
```
Comment (NullVoxPopuli) [inline test/adapter/json_api/linked_test.rb]: nested serializers :-)

File: lib/active_model/serializer/adapter/json_api.rb (hunk 1 above)
Comment (hut8) [inline lib/active_model/serializer/adapter/json_api.rb]:
```
[7] pry(main)> lol ||= []
[]
[8] pry(main)> lol |= [1,2,3]
[
    [0] 1,
    [1] 2,
    [2] 3
]
[9] pry(main)> lol
[
    [0] 1,
    [1] 2,
    [2] 3
]
```

It's fancy syntax for a union

Comment (NullVoxPopuli) [inline lib/active_model/serializer/adapter/json_api.rb]: woah. that is fancy. TIL

**Comment by beauby** [comment]
Rebased.

File: lib/active_model/serializer/adapter/json_api.rb [hunk 4]
```diff
@@ -81,16 +81,18 @@ def fragment_cache(cached_hash, non_cached_hash)
...
+            next unless result[:included]
 
-            if result[:included]
-              hash[:included] ||= []
-              hash[:included] |= result[:included]
-            end
+            included |= result[:included]
           end
 
+          included.delete_if { |resource| hash[:data].include?(resource) }
```
Comment (joaomdmoura) [inline lib/active_model/serializer/adapter/json_api.rb]: I see we are deleting here the duplicated resource, but it seems hacky, it's not addressing the problem itself, just working around it, did you found the main issue causing this?

File: lib/active_model/serializer/adapter/json_api.rb [hunk 5]
```diff
@@ -171,31 +174,31 @@ def relationships_for(serializer)
...
 
-            primary_data = primary_data_for(serializer)
+            resource_object = primary_data_for(serializer)
             relationships = relationships_for(serializer)
-            primary_data[:relationships] = relationships if relationships.any?
+            resource_object[:relationships] = relationships if relationships.any?
 
-            return if included.include?(primary_data)
-            included.push(primary_data)
+            return if included.include?(resource_object) || primary_data.include?(resource_object)
```
Comment (joaomdmoura) [inline lib/active_model/serializer/adapter/json_api.rb]: :+1:

File: test/adapter/json_api/linked_test.rb (hunk 3 above)
Comment (joaomdmoura) [inline test/adapter/json_api/linked_test.rb]: Would be nice to have another scenario using non-nested serializers :smile:

File: lib/active_model/serializer/adapter/json_api.rb (hunk 4 above)
Comment (beauby) [inline lib/active_model/serializer/adapter/json_api.rb]: It is a structural issue. When the primary resource is a single resource (`serializable_hash_for_single_resource`), we make sure we do not add to `included` any related resource that is the primary resource. However, when the primary resource is a collection (`serializable_hash_for_collection`), the adapter works by computing the hash for every resource independently, and then combining the hashes into a big one. This has the advantage of clear code, but the disadvantage that when serializing `[a, b]` where `a` includes `b`, we have no other choice than manually removing duplicates when aggregating.

**Comment by joaomdmoura** [comment]
@beauby just checked it, made few comments on it for you to check

File: test/adapter/json_api/linked_test.rb (hunk 3 above)
Comment (beauby) [inline test/adapter/json_api/linked_test.rb]: We need #1225 for that. The reason is that if we do not use nested serializers here, we have a namespacing issue. With #1225, we can declare the serializers in a non-nested way and it will still use the right one.

**Comment by beauby** [comment]
@joaomdmoura Answered ;)

File: lib/active_model/serializer/adapter/json_api.rb (hunk 4 above)
Comment (joaomdmoura) [inline lib/active_model/serializer/adapter/json_api.rb]: got it :wink:

**Comment by joaomdmoura** [comment]
LGTM :+1:

File: test/adapter/json_api/linked_test.rb [hunk 6]
```diff
@@ -1,11 +1,16 @@
 require 'test_helper'
+
+NestedPost = Class.new(Model)
+class NestedPostSerializer < ActiveModel::Serializer
```
Comment (NullVoxPopuli) [inline test/adapter/json_api/linked_test.rb]: I'd say because this model *and* serializer are created here, and specific to this test, they should be namespaced under the test. :-\

File: lib/active_model/serializer/adapter/json_api.rb [hunk 7]
```diff
@@ -102,9 +104,10 @@ def serializable_hash_for_collection(options)
         def serializable_hash_for_single_resource
           primary_data = primary_data_for(serializer)
           relationships = relationships_for(serializer)
-          included = included_resources(@include_tree)
+          primary_data[:relationships] = relationships if relationships.any?
```
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: simple refactor, nice

File: lib/active_model/serializer/adapter/json_api.rb [hunk 8]
```diff
@@ -102,9 +104,10 @@ def serializable_hash_for_collection(options)
...
           hash = { data: primary_data }
-          hash[:data][:relationships] = relationships if relationships.any?
+
+          included = included_resources(@include_tree, [primary_data])
```
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: so, `included_resources` now takes in `[primary_data]` as a second argument

File: lib/active_model/serializer/adapter/json_api.rb [hunk 9]
```diff
@@ -171,31 +174,31 @@ def relationships_for(serializer)
           end
         end
 
-        def included_resources(include_tree)
+        def included_resources(include_tree, primary_data)
           included = []
 
           serializer.associations(include_tree).each do |association|
-            add_included_resources_for(association.serializer, include_tree[association.key], included)
+            add_included_resources_for(association.serializer, include_tree[association.key], primary_data, included)
```
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: and `add_included_resources_for` passes `primary_data` through

File: lib/active_model/serializer/adapter/json_api.rb (hunk 8 above)
Comment (beauby) [inline lib/active_model/serializer/adapter/json_api.rb]: Yes, this is to ensure, preemptively, that we do not include any of the primary data in the `included` hash when building the hash for a single resource.

File: lib/active_model/serializer/adapter/json_api.rb [hunk 10]
```diff
@@ -171,31 +174,31 @@ def relationships_for(serializer)
...
           end
 
           included
         end
 
-        def add_included_resources_for(serializer, include_tree, included)
+        def add_included_resources_for(serializer, include_tree, primary_data, included)
           if serializer.respond_to?(:each)
-            serializer.each { |s| add_included_resources_for(s, include_tree, included) }
+            serializer.each { |s| add_included_resources_for(s, include_tree, primary_data, included) }
```
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: and primary_data (which is `[primary_data]`) is a new argument to `add_included_resources_for`

File: lib/active_model/serializer/adapter/json_api.rb [hunk 11]
```diff
@@ -171,31 +174,31 @@ def relationships_for(serializer)
...
           else
             return unless serializer && serializer.object
 
-            primary_data = primary_data_for(serializer)
+            resource_object = primary_data_for(serializer)
             relationships = relationships_for(serializer)
-            primary_data[:relationships] = relationships if relationships.any?
+            resource_object[:relationships] = relationships if relationships.any?
```
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: nice refactor

File: lib/active_model/serializer/adapter/json_api.rb (hunk 5 above)
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: And we add `primary_data.include?(resource_object)` ( which is true when `[primary_data].include(resource_object)` which is approx `[primary_data_for(serializer).update(relationships: relationships_for(serializer))].include(primary_data_for(serializer)update(relationships: relationships_for(serializer))`) i.e. primary data is for same serializer) as condition to return early

File: lib/active_model/serializer/adapter/json_api.rb [hunk 12]
```diff
@@ -171,31 +174,31 @@ def relationships_for(serializer)
...
 
-            return if included.include?(primary_data)
-            included.push(primary_data)
+            return if included.include?(resource_object) || primary_data.include?(resource_object)
+            included.push(resource_object)
 
             serializer.associations(include_tree).each do |association|
-              add_included_resources_for(association.serializer, include_tree[association.key], included)
+              add_included_resources_for(association.serializer, include_tree[association.key], primary_data, included)
```
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: and pass along our `[primary_data]` again to `add_included_resources_for`

File: test/adapter/json_api/linked_test.rb (hunk 6 above)
Comment (bf4) [inline test/adapter/json_api/linked_test.rb]: I think we agree we'll start doing that soon

File: lib/active_model/serializer/adapter/json_api.rb [hunk 13]
```diff
@@ -81,16 +81,18 @@ def fragment_cache(cached_hash, non_cached_hash)
...
           serializer.each do |s|
             result = self.class.new(s, instance_options.merge(fieldset: fieldset)).serializable_hash(options)
             hash[:data] << result[:data]
+            next unless result[:included]
 
-            if result[:included]
-              hash[:included] ||= []
-              hash[:included] |= result[:included]
-            end
+            included |= result[:included]
```
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: refactor

File: lib/active_model/serializer/adapter/json_api.rb (hunk 4 above)
Comment (bf4) [inline lib/active_model/serializer/adapter/json_api.rb]: deletes resource from `included` if is a root resource

this included stuff is getting messy. needs a refactor before it sends even more vines through the class

Comment (beauby) [inline lib/active_model/serializer/adapter/json_api.rb]: I believe it is the best we can achieve without refactoring the adapter so that it does not call itself recursively for collections (which I'm in favor of, in a subsequent PR). The scope of this PR was to fix a behavior breaking JSON API spec, without modifying the adapter too much.

**Comment by bf4** [comment]
I'm ok to merge, but we need to admit that this inclusion stuff has been a source of bugs and increasing complexity.  IMHO, it deserves its own object

**Comment by beauby** [comment]
@bf4 We agree. I'm happy to work on a refactor once this is merged.

File: test/adapter/json_api/linked_test.rb (hunk 6 above)
Comment (beauby) [inline test/adapter/json_api/linked_test.rb]: Yes. Let's leave them there for now, and take care of it during the Great Test Refactor.
