### PR TITLE
Fixes #1211, include_tree is null when using the key: options

### LINKED ISSUE #1211: NoMethodError: undefined method `key?' for nil:NilClass when using key
I was actually just trying to update my other pull request and was figuring out exactly what the "include" parameter expects for including related entities with JSON-API. Then I think I found a bug.

**Exception**

```
Frame number: 33/115
Frame type: method

From: /home/liam/fund-map/app/controllers/api_controller.rb @ line 8 ApiController#render_api:

    6: def render_api model
    7:   model = model.page(params[:page]) if model.is_a? ActiveRecord::Relation
 => 8:   render json: model, include: params[:include]
    9: end

NoMethodError: undefined method `key?' for nil:NilClass
from /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb:95:in `block (2 levels) in associations'
[1] pry(#<Api::V1::OrganizationsController>)> wtf
Exception: NoMethodError: undefined method `key?' for nil:NilClass
--
0: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb:95:in `block (2 levels) in associations'
1: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb:94:in `each'
2: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb:94:in `block in associations'
3: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/adapter/json_api.rb:156:in `each'
4: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/adapter/json_api.rb:156:in `each'
--

```

**Working Steps**

I have a model that has this:
```ruby
has_many :organization_mappings
```

When I hit a route that invokes this code, it works great:

```
@organizations = Organization.all
render json: @organizations, include: 'organization_mappings'
```

**Broken Steps**

I have another model that has a `[model_name]_mappings` relationship, so be less redundant, I changed the `has_many` line to have a key:

```
  has_many :organization_mappings, key: :mappings
```

I figured that I would probably want to do this:

```
@organizations = Organization.all
render json: @organizations, include: 'mappings'
```

but that includes nothing. So then I tried the original, `include: 'organization_mappings'`, and it gave me the exception from above.

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Fixes #1211, and Closes #1212

Thanks @hut8 for the failing test!

### CODE REVIEW

File: lib/active_model/serializer/associations.rb [hunk 1]
```diff
@@ -92,7 +92,7 @@ def associations(include_tree = DEFAULT_INCLUDE_TREE)
 
         Enumerator.new do |y|
           self.class._reflections.each do |reflection|
-            next unless include_tree.key?(reflection.name)
+            next unless include_tree.try(:key?, reflection.name)
```
Comment (beauby) [inline lib/active_model/serializer/associations.rb]: This fix is not right, because then you can never explicitly include an association with a custom key.

Comment (beauby) [inline lib/active_model/serializer/associations.rb]: Clearly, the test should be on `reflection.key` instead of `reflection.name` in order to handle custom keys (`reflection.key` falls back to `reflection.name` anyways if one was not provided). I'm still trying to understand what caused `include_tree` to be `nil` though.

File: lib/active_model/serializer/associations.rb [hunk 2]
```diff
@@ -92,7 +92,8 @@ def associations(include_tree = DEFAULT_INCLUDE_TREE)
 
         Enumerator.new do |y|
           self.class._reflections.each do |reflection|
-            next unless include_tree.key?(reflection.name)
+            name = reflection.options.fetch(:key, reflection.name)
+            next unless include_tree.try(:key?, name)
```
Comment (beauby) [inline lib/active_model/serializer/associations.rb]: No need for `.try` here, as this method is not supposed to be called with a `nil` `IncludeTree`.

File: lib/active_model/serializer/associations.rb [hunk 3]
```diff
@@ -92,7 +92,8 @@ def associations(include_tree = DEFAULT_INCLUDE_TREE)
 
         Enumerator.new do |y|
           self.class._reflections.each do |reflection|
-            next unless include_tree.key?(reflection.name)
+            name = reflection.options.fetch(:key, reflection.name)
```
Comment (beauby) [inline lib/active_model/serializer/associations.rb]: This local var should probably be named `key` rather than `name`.

File: test/action_controller/json_api/linked_test.rb [hunk 4]
```diff
@@ -137,6 +142,12 @@ def test_render_resource_with_nested_has_many_include
           assert_equal expected_linked, response['included']
         end
 
+        def test_render_resource_with_include_of_custom_key_by_original
+          get :render_resource_with_include_of_custom_key_by_original
+          response = JSON.parse(@response.body)
+          assert response.key? 'included'
```
Comment (beauby) [inline test/action_controller/json_api/linked_test.rb]: Here I think it's worth checking whether the overridden key is present as well (i.e. `responce['included']['reviews']`).

Comment (NullVoxPopuli) [inline test/action_controller/json_api/linked_test.rb]: I had, that... don't know why I got rid of. 

Coding when tired leads to silly things

Comment (NullVoxPopuli) [inline test/action_controller/json_api/linked_test.rb]: oh hey, this is what I found, so now we get to talk about what's supposed to happen :-)

```
  {
    "data"=>{
      "id"=>"1", "type"=>"posts", 
      "relationships"=>{
        "reviews"=>{"data"=>[{"id"=>"1", "type"=>"comments"}, {"id"=>"2", "type"=>"comments"}]},
        "writer"=>{"data"=>{"id"=>"1", "type"=>"authors"}}, 
        "site"=>{"data"=>{"id"=>"1", "type"=>"blogs"}}}}, 
    "included"=>[
      {"id"=>"1", "type"=>"comments", "attributes"=>{"body"=>"ZOMG A COMMENT"},
       "relationships"=>{"post"=>{"data"=>{"id"=>"1", "type"=>"posts"}}, "author"=>{"data"=> {"id"=>"2", "type"=>"authors"}}}}, 

      {"id"=>"2", "type"=>"comments", "attributes"=>{"body"=>"ZOMG ANOTHER COMMENT"}, "relationships"=>{"post"=>{"data"=>{"id"=>"1", "type"=>"posts"}}, "author"=>{"data"=>nil}}}]}


so, the `key` is specified in `relationships`, but the only thing related in `included` is the `type`, but I don't think that should change with `key`?

File: lib/active_model/serializer/associations.rb (hunk 3 above)
Comment (bf4) [inline lib/active_model/serializer/associations.rb]: lgtm, though we need to be careful with this include_tree code. It's introduced some bugs and complexity

File: test/action_controller/json_api/linked_test.rb (hunk 4 above)
Comment (beauby) [inline test/action_controller/json_api/linked_test.rb]: Sorry, I was half asleep when I posted this. I meant, check that `included` is here and that `hash[:data][:relationships][:reviews]` is here as well.

File: lib/active_model/serializer/associations.rb (hunk 3 above)
Comment (beauby) [inline lib/active_model/serializer/associations.rb]: What are the other bugs introduced with `IncludeTree`?

Comment (NullVoxPopuli) [inline lib/active_model/serializer/associations.rb]: The tests say none. :-)

The beauty (and curse) of the test suite is that they'll catch the bugs for us (as long as we have the right tests)

File: test/action_controller/json_api/linked_test.rb (hunk 4 above)
Comment (NullVoxPopuli) [inline test/action_controller/json_api/linked_test.rb]: done :-)

**Comment by NullVoxPopuli** [comment]
ok, hopefully the build passes.

any other out standing concerns?

File: lib/active_model/serializer/associations.rb [hunk 5]
```diff
@@ -92,7 +92,8 @@ def associations(include_tree = DEFAULT_INCLUDE_TREE)
 
         Enumerator.new do |y|
           self.class._reflections.each do |reflection|
-            next unless include_tree.key?(reflection.name)
+            key = reflection.options.fetch(:key, reflection.name)
+            next unless include_tree.key?(key)
```
Comment (beauby) [inline lib/active_model/serializer/associations.rb]: :+1:

File: CHANGELOG.md [hunk 6]
```diff
@@ -21,6 +21,7 @@ Features:
 Fixes:
 
 Misc:
+- [#1214](https://github.com/rails-api/active_model_serializers/pull/1214) retrieve the key from the reflection options when building associations (@NullVoxPopuli, @hut8)
```
Comment (beauby) [inline CHANGELOG.md]: That should probably be under `Fixes:`.

File: test/action_controller/json_api/linked_test.rb [hunk 7]
```diff
@@ -137,6 +142,18 @@ def test_render_resource_with_nested_has_many_include
...
+
+          relationships = response['data']['relationships']
+
+          assert relationships.key? 'reviews'
+          assert relationships.key? 'writer'
```
Comment (beauby) [inline test/action_controller/json_api/linked_test.rb]: Let's just test for what we are interested in, i.e. `reviews`. The rest should be ensured by other tests.
Also, use `assert_include` as it has better reporting format.

Comment (NullVoxPopuli) [inline test/action_controller/json_api/linked_test.rb]: well, all 3 of them are for different types of associations. I'll change to assert_include though

File: CHANGELOG.md (hunk 6 above)
Comment (bf4) [inline CHANGELOG.md]: yup!

Comment (NullVoxPopuli) [inline CHANGELOG.md]: oh, I misunderstood ha. I thought misc was under fixes. I'll update.

**Comment by NullVoxPopuli** [comment]
yay it passed!

**Comment by NullVoxPopuli** [comment]
rebased

**Comment by beauby** [comment]
LGTM, let's squash and merge.

**Comment by NullVoxPopuli** [comment]
done

**Comment by NullVoxPopuli** [comment]
the author says hut8, should that be changed? he did point out the issue and gave us a failing test :-)

**Comment by beauby** [comment]
He did point out the issue so that seems fair.

**Comment by hut8** [comment]
I'm fine with @NullVoxPopuli being the author. I wrote the failing test but he fixed it which is really what counts.

**Comment by NullVoxPopuli** [comment]
@hut8, I'm leaving you as the author, to show how thankful we are that you found the bug, and gave us the test. :-)
