### PR TITLE
Use serializer name instead of model name to create fragment cache serializers

### LINKED ISSUE #1621: Superclass absorbs subclass attributes when using inherited serializers with fragment caching
#### Expected behavior vs actual behavior

Normally, adding attributes to an inherited serializer does not effect the base serializer. For example

```ruby
class FooSerializer < ActiveModel::Serializer
  attributes :id
end

class SpecialFooSerializer < FooSerializer
  attribute :name
end
```

In this case, `Foo`s serialized with the `SpecialFooSerializer` would gain the "name" field in the serialization, while `Foo`s serialized with the `FooSerializer` will not. This behavior is broken when using a fragment cache, because the Cached/NonCached serializers are made by model name, not serializer name. If you serialize a `Foo` with the `SpecialFooSerializer`, then internally a `FooCachedSerializer` is made which will be used for subsequent serializations of `Foo`s, whether they use the base serializer or not.

#### Steps to reproduce

Paste this into a Rails terminal. You'll see that both of the elements in the array are the same at the end, even though the second element should not have the name attribute.

```ruby
class Foo 
  include ActiveModel::Model
  attr_accessor :id, :name

  def read_attribute_for_serialization(attr)
    send attr
  end
end

class FooSerializer < ActiveModel::Serializer
  attributes :id
  cache key: 'foo', only: [:id]
end

class SpecialFooSerializer < FooSerializer
  attribute :name
  cache key: 'special_foo', only: [:id, :name]
end

foo = Foo.new id: 1, name: 'Test'

[
  ActiveModel::SerializableResource.new(foo, serializer: SpecialFooSerializer).serializable_hash,
  ActiveModel::SerializableResource.new(foo).serializable_hash
]
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 0.10.0.rc4

Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

OS Type & Version: OS X El Capitan

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails

### PR DESCRIPTION
**Pull request by lserman**
Fixes #1621

### CODE REVIEW

**Comment by groyoh** [comment]
Thanks for this PR! I've been wanting to roll it out myself for quite some time now. Could you add an entry within the CHANGELOG in the `fixes` section?

File: test/fixtures/poro.rb [hunk 1]
```diff
@@ -139,6 +139,11 @@ def slug
   belongs_to :author
 end
 
+InheritedRoleSerializer = Class.new(RoleSerializer) do
```
Comment (groyoh) [inline test/fixtures/poro.rb]: Could you move this class to `test/cache_test.rb` to avoid bloating this file?

File: CHANGELOG.md [hunk 2]
```diff
@@ -24,6 +24,7 @@ Features:
 - [#1340](https://github.com/rails-api/active_model_serializers/pull/1340) Add support for resource-level meta. (@beauby)
 
 Fixes:
+- [#1622](https://github.com/rails-api/active_model_serializers/pull/1622) Fix inherited serializers when using fragment cache
```
Comment (bf4) [inline CHANGELOG.md]: `Fix fragment caching inheriting serializers to use distinct per-serializer caches. (@Iserman)`

File: lib/active_model_serializers/fragment_cache.rb [hunk 3]
```diff
@@ -79,10 +79,10 @@ def add_attributes_to_serializer(serializer, attributes, attributes_keys)
     #     User_AdminCachedSerializer
     #     User_AdminNonCachedSerializer
     #
-    def fragment_serializer(name)
+    def fragment_serializer
       klass      = serializer.class
-      cached     = "#{to_valid_const_name(name)}CachedSerializer"
-      non_cached = "#{to_valid_const_name(name)}NonCachedSerializer"
+      cached     = "Cached#{to_valid_const_name(klass.name)}"
```
Comment (bf4) [inline lib/active_model_serializers/fragment_cache.rb]: while in here, would you mind rewriting as

```ruby
serializer_class_name = to_valid_const_name(klass.name)
cached = "Cached#{serializer_class_name}"
non_cached = "NonCached#{serializer_class_name}"
```

**Comment by bf4** [comment]
@lserman awesome work! Please address comments, squash down to one commit, and this is ready to merge! :100:

**Comment by lserman** [comment]
@bf4 thank you, hope I did that squash right... never done this before.

File: test/cache_test.rb [hunk 4]
```diff
@@ -1,6 +1,12 @@
 require 'test_helper'
 require 'tmpdir'
 require 'tempfile'
+
+InheritedRoleSerializer = Class.new(RoleSerializer) do
+  cache key: 'inherited_role', only: [:name, :special_attribute]
+  attribute :special_attribute
+end
```
Comment (bf4) [inline test/cache_test.rb]: Better to include this in the `class CacheTest` so it's not in the global scope, but not a blocker

File: test/cache_test.rb [hunk 5]
```diff
@@ -150,6 +156,14 @@ def test_fragment_fetch_with_virtual_associations
       assert_equal({ place: 'Nowhere' }, ActionController::Base.cache_store.fetch(@location.cache_key))
     end
 
+    def test_fragment_cache_with_inheritance
+      inherited = render_object_with_cache(@role, serializer: InheritedRoleSerializer)
+      base = render_object_with_cache(@role)
+
+      assert_includes(inherited.keys, :special_attribute)
```
Comment (bf4) [inline test/cache_test.rb]: minitest asserts are in the reverse order: expected, actual

**Comment by bf4** [comment]
@lserman :100: you're doing a fantastic job!

File: test/cache_test.rb (hunk 5 above)
Comment (lserman) [inline test/cache_test.rb]: Not sure what you mean here, should I not use assert_includes? Or am I misunderstanding this method? http://apidock.com/ruby/v1_9_3_392/MiniTest/Assertions/assert_includes

Comment (bf4) [inline test/cache_test.rb]: You're right. That's annoying asser_equal is reverse order

File: lib/active_model_serializers/fragment_cache.rb [hunk 6]
```diff
@@ -79,10 +79,12 @@ def add_attributes_to_serializer(serializer, attributes, attributes_keys)
     #     User_AdminCachedSerializer
```
Comment (groyoh) [inline lib/active_model_serializers/fragment_cache.rb]: The doc should also be changed accordingly :wink:

File: CHANGELOG.md [hunk 7]
```diff
@@ -26,6 +26,7 @@ Features:
 - [#1340](https://github.com/rails-api/active_model_serializers/pull/1340) Add support for resource-level meta. (@beauby)
 
 Fixes:
+- [#1622](https://github.com/rails-api/active_model_serializers/pull/1622) Fix fragment caching inherited serializers to use distinct per-serializer caches. (@lserman)
```
Comment (groyoh) [inline CHANGELOG.md]: I'm not too happy with this sentence though. Hard to understand what was the actual change. I'd prefer something closer to the PR title e.g. `Fragment cache now fragments based on the serializer name instead of the model name`.

@bf4 do you agree or am I being too picky here? :smile:

Comment (bf4) [inline CHANGELOG.md]: @groyoh No, not being too picky. The problem with not mentioning inheritance is that without it there fix is unclear.  btw, I've also struggled with what the description should be https://github.com/rails-api/active_model_serializers/pull/1622/files/038f3fc91d103aee0a14dc725b4856bf86a0a0ad#r57530684

Comment (groyoh) [inline CHANGELOG.md]: Yeah, but that's not the only thing it solve actually. If you define two serializers with the same model, you would get the same issue. That's actually what prevented me to properly refactor fragment cache in #1565.

Comment (bf4) [inline CHANGELOG.md]: Good point.  So, `Records are now fragment cached by serializer name,  rather that model name, allowing multiple fragment caches for a model.`

**Comment by bf4** [comment]
Merged! :rainbow: @lserman
