### PR TITLE
Fix #1759, Grape integration, adds serialization_context

### LINKED ISSUE #1759: `Grape::ActiveModelSerializers` raises exception on missing serialization_context
#### Expected behavior vs actual behavior

Per https://github.com/rails-api/active_model_serializers/issues/1268#issuecomment-222360982 and https://github.com/rails-api/active_model_serializers/issues/1268#issuecomment-211497074

The AMS Grape adapter does not pass in `serialization_context`, which is required to generate JsonApi pagination links, which raises an exception.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*:  `0.10.0`

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `2.2.0`

OS Type & Version: `Mac, Yosemite`

Integrated application and version *(e.g., Rails, Grape, etc)*: `Grape`, but version unknown

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

```
"status":500
    "title":"Internal Server Error"
    "detail":"key not found: :serialization_context"
    "meta":{"error_class":"KeyError"
    "backtrace":
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/adapter/json_api/pagination_links.rb:12:in `fetch'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/adapter/json_api/pagination_links.rb:12:in `initialize'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/adapter/json_api.rb:506:in `new'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/adapter/json_api.rb:506:in `pagination_links_for'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/adapter/json_api.rb:131:in `success_document'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/adapter/json_api.rb:48:in `serializable_hash'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/adapter/base.rb:29:in `as_json'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/serializable_resource.rb:8:in `to_json'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/serializable_resource.rb:8:in `to_json'"
    "~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0/lib/active_model_serializers/logging.rb:6
```

### PR DESCRIPTION
**Pull request by bf4**
- improves improves serialization_context to take options and not depend
on a `request` object.
- adds descriptive error on missing serialization_context.
- Document overriding `CollectionSerializer#paginated?`.

Closes #1759

### CODE REVIEW

File: lib/active_model_serializers/adapter/json_api.rb [hunk 1]
```diff
@@ -505,6 +505,7 @@ def links_for(serializer)
       # prs:
       #   https://github.com/rails-api/active_model_serializers/pull/1041
       def pagination_links_for(serializer)
+        return {} unless instance_options.key?(:serialization_context)
```
Comment (beauby) [inline lib/active_model_serializers/adapter/json_api.rb]: Why not put this test [there](https://github.com/bf4/active_model_serializers/blob/9b77f0af2928051e81984bce96dc365e7adb4cda/lib/active_model_serializers/adapter/json_api.rb#L129)?

Comment (bf4) [inline lib/active_model_serializers/adapter/json_api.rb]: ref:

```ruby

        if is_collection && serializer.paginated?
          hash[:links] ||= {}
          hash[:links].update(pagination_links_for(serializer))
        end
```

I did at first, but then I was thinking it's really tightly coupled to the paginationlinks object and it's intent isn't as obvious in the conditional.

But really we shouldn't let an empty serialization_context get in that far.  This is a quick fix, but the better fix is at the boundary, I think

**Comment by bf4** [comment]
I spent too much time on this.  Any blockers or anyone want to make changes?

**Comment by bf4** [comment]
cc @onomated @hut8

**Comment by onomated** [comment]
@bf4 Sorry for the delay.  Just seeing this, was a holiday weekend.  I'll take a look and report any changes back

File: lib/active_model_serializers/adapter/json_api/pagination_links.rb [hunk 2]
```diff
@@ -2,14 +2,20 @@ module ActiveModelSerializers
...
         FIRST_PAGE = 1
 
         attr_reader :collection, :context
 
         def initialize(collection, adapter_options)
           @collection = collection
           @adapter_options = adapter_options
-          @context = adapter_options.fetch(:serialization_context)
+          @context = adapter_options.fetch(:serialization_context) do
+            fail MissingSerializationContextError, 'JsonApi::PaginationLinks requires a'\
```
Comment (groyoh) [inline lib/active_model_serializers/adapter/json_api/pagination_links.rb]:
```diff
-            fail MissingSerializationContextError, 'JsonApi::PaginationLinks requires a'\
+            fail MissingSerializationContextError, 'JsonApi::PaginationLinks requires a '\
 
```

File: lib/active_model_serializers/adapter/json_api/pagination_links.rb [hunk 3]
```diff
@@ -2,14 +2,20 @@ module ActiveModelSerializers
...
+              "ActiveModelSerializers::SerializationContext.\n"\
+              "Please pass a ':serialization_context' option or override CollectionSerializer#paginated?"\
```
Comment (groyoh) [inline lib/active_model_serializers/adapter/json_api/pagination_links.rb]:
```diff
-              "Please pass a ':serialization_context' option or override CollectionSerializer#paginated?"\
+              "Please pass a ':serialization_context' option or override CollectionSerializer#paginated? "\
```

File: lib/active_model_serializers/adapter/json_api/pagination_links.rb (hunk 2 above)
Comment (groyoh) [inline lib/active_model_serializers/adapter/json_api/pagination_links.rb]: `'` is use for defining the string here whereas `"` is used below. Not sure if typo or if I'm missing something ;)

Comment (bf4) [inline lib/active_model_serializers/adapter/json_api/pagination_links.rb]: just because I have things in the others that need double quotes. rubocop caught it.  changing to a heredoc

File: lib/grape/helpers/active_model_serializers.rb [hunk 4]
```diff
@@ -8,6 +11,12 @@ module ActiveModelSerializers
       #
       # Example: To include pagination meta data: render(posts, meta: { page: posts.page, total_pages: posts.total_pages })
       def render(resource, active_model_serializer_options = {})
+        active_model_serializer_options.fetch(:serialization_context) do
+          active_model_serializer_options[:serialization_context] = ::ActiveModelSerializers::SerializationContext.new(
+            original_url: request.url[/\A[^?]+/],
```
Comment (onomated) [inline lib/grape/helpers/active_model_serializers.rb]: `original_url` option should be `request_url`

**Comment by onomated** [comment]
So the current solution works when an explicit `render` call is made on a resource.  In generally, grape formatters should render the resulting resource without options.  For example,
```
resource :statuses do
      desc 'Return a public timeline.'
      get :public_timeline do
        Status.limit(20)
      end
end
```
returns the `MissingSerializationContextError` error since there wasn't an explicit render call.  This works if `Status.limit(20)` is wrapped in a render as `render(Status.limit(20))`.  
Moving the creation of the serialization context to the formatter will fix this, and allow including other AMS options such the **serialization scope**.  As done in the [grape_active-model-serializers gem](https://raw.githubusercontent.com/ruby-grape/grape-active_model_serializers/master/lib/grape-active_model_serializers/formatter.rb)
I can take a stab at addressing this if you give me write access @bf4, or I can create a new PR on this branch

**Comment by bf4** [comment]
@onomated if you would make a PR into my branch, that would be fantastic!  I didn't check if I had all the objects I need in the formatter

File: lib/grape/helpers/active_model_serializers.rb (hunk 4 above)
Comment (bf4) [inline lib/grape/helpers/active_model_serializers.rb]: oops :)  

Also 👍 to making a PR to my branch and moving this code to the formatter (and adding yourself in the changelog!) https://github.com/rails-api/active_model_serializers/pull/1754#issuecomment-222990205

Comment (bf4) [inline lib/grape/helpers/active_model_serializers.rb]: I also wasn't able to duplicate the failure in the grape tests, so if you could do that, that would be fantastic!

Comment (bf4) [inline lib/grape/helpers/active_model_serializers.rb]: (I don't use grape)

**Comment by bf4** [comment]
@onomated I just [merged in your PR](https://github.com/bf4/active_model_serializers/pull/4) and will finish this up. Great work 💯

File: lib/active_model_serializers/adapter/json_api/pagination_links.rb [hunk 5]
```diff
@@ -2,14 +2,21 @@ module ActiveModelSerializers
   module Adapter
     class JsonApi < Base
       class PaginationLinks
+        MissingSerializationContextError = Class.new(KeyError)
```
Comment (beauby) [inline lib/active_model_serializers/adapter/json_api/pagination_links.rb]: Should this be defined within `PaginationLinks`? It seems like it's more general than that.

File: lib/active_model_serializers/adapter/json_api/pagination_links.rb [hunk 6]
```diff
@@ -2,14 +2,21 @@ module ActiveModelSerializers
...
 
         def initialize(collection, adapter_options)
           @collection = collection
           @adapter_options = adapter_options
-          @context = adapter_options.fetch(:serialization_context)
+          @context = adapter_options.fetch(:serialization_context) do
+            fail MissingSerializationContextError, <<-EOF.freeze
+ JsonApi::PaginationLinks requires a ActiveModelSerializers::SerializationContext.
+ Please pass a ':serialization_context' option or
+ override CollectionSerializer#paginated? to return 'false'.
```
Comment (beauby) [inline lib/active_model_serializers/adapter/json_api/pagination_links.rb]: That sucks for the poor guy who just does not care about pagination. Shouldn't we disable pagination by default?

**Comment by beauby** [comment]
See my 2 remarks. LGTM otherwise.

File: lib/active_model_serializers/adapter/json_api/pagination_links.rb (hunk 6 above)
Comment (bf4) [inline lib/active_model_serializers/adapter/json_api/pagination_links.rb]: Well, it's only enabled for paginatable objects, so saying 'def paginated? false; end doesn't seem terrible to me.  Maybe a serializer option 'paginate: false'?  I wonder if that's already a thing in other gems...

B mobile phone

File: lib/active_model_serializers/adapter/json_api/pagination_links.rb (hunk 5 above)
Comment (bf4) [inline lib/active_model_serializers/adapter/json_api/pagination_links.rb]: I'm happy to put a guard wherever it's to be used...  Can't think of a better spot...

**Comment by bf4** [comment]
@onomated https://github.com/bf4/active_model_serializers/pull/4#issuecomment-225712331 so is this good for you?

**Comment by onomated** [comment]
@bf4 couldn't quite resolve the comment link in the @mention above, but on the general topic of pagination, it'll be awesome if this was configurable like so `paginate: false` as opposed to `serialization_context: nil`.  I personally am in the party of not caring about pagination in the json-api rendition.  I currently rely on my internal header pagination implemented a while back.  With the fixes in this PR, Grape support has pagination support out the box so it just works for new projects but currently no way to turn this off if its not desired.

**Comment by bf4** [comment]
@onomated I just rebased this off of master. Can you confirm it works for you before merge?

**Comment by onomated** [comment]
@bf4 sure thing.  Checking out now

**Comment by onomated** [comment]
@bf4 All good!  👍 💯

**Comment by xn** [comment]
Oh snap! Thanks, this is awesome!

**Comment by bf4** [comment]
Thanks @onomated for your work here.  This was actually a blocker for us for releasing 0.10.1

**Comment by xn** [comment]
Just want to leave this here in case someone gets stuck with an error like: `NoMethodError: undefined method `url' for nil:NilClass`. 

This formatter now depends on `Grape::Middleware::Globals`
You can get that going like:
```
module MyApi
  class ApiBase < Grape::API
    use Grape::Middleware::Globals
    require 'grape/active_model_serializers'
    include Grape::ActiveModelSerializers
    mount MyApi::V1::ApiBase
```

or minimally:
```
class API < Grape::API
  # @note Make sure this is above you're first +mount+
  use Grape::Middleware::Logger
end
```

**Comment by onomated** [comment]
@xn, I didn't encounter this as I use some other middleware that inherits from grape globals.  Should this be mixed in as part of `include Grape::ActiveModelSerializers`?

**Comment by xn** [comment]
Well, if you just add it to the docs, then if someone wants/needs to monkey with `Grape::Middleware::Globals` or write their own for whatever reasons, they are free to do so without having to monkey with this formatter as well.

**Comment by bf4** [comment]
PRs accepted :)

**Comment by xn** [comment]
@bf4 I'm happy to roll this into a documentation PR. Though I think it is better to allow the developer to meet the dependency, it is a question that should be answered by someone who has a stake in the project's maintainance/architecture.

**Comment by bf4** [comment]
Not sure I follow.  Do you think there is a problem in AMS impl or just docs needed?

B mobile phone

**Comment by xn** [comment]
AMS is kindly creating a grape formatter. Said formatter is depending on a grape middleware that is not enabled by default. You have a choice to automatically meet the dependency by hardcoding that dependency in or document the dependency to let the developer meet it own their own terms.

If I am being to circuitous, I apologize. Let me know and I will tell you what I believe should be done.

**Comment by bf4** [comment]
I don't use grape, so I don't know what's right for you

**Comment by xn** [comment]
Ok, from basic OO principles you should let the developer meet the dependency. So, I'll create a PR for documentation to meet this in the README.

**Comment by xn** [comment]
#1818
