### PR TITLE
JSON:API relationship tests no longer show v0.10.5 regression

### LINKED ISSUE #2125: 0.10.6: type attribute not respected on belongs to relations
When using a custom `type` on a serializer, the type is not used on nested belongs to relations.
This only happens with belongs_to relationships, has_many relationships are working fine.

```ruby
class Foo < ActiveRecord::Base
end

class Bar < ActiveRecord::Base
  belongs_to :foo
end

class FooSerializer < ActiveModel::Serializer
  type 'custom-type'
end

class BarSerializer < ActiveModel::Serializer
end
```

#### Expected behavior vs actual behavior

Expected:

```json
{ "data": { "relationships": { "foo": { "data": { "id": 1, "type": "custom-type" } } } }
```

Actual:

```json
{ "data": { "relationships": { "foo": { "data": { "id": 1, "type": "foos" } } } }
```

As it's working fine on 0.10.5, it seems to be a regression of 0.10.6

### LINKED ISSUE #2160: JSONAPI - Wrong "type" for belongs_to polymorphic relationships
#### Expected behavior vs actual behavior

For JSONAPI, after this pr is merged: #1857, `type` parameter returns the relation type, instead of resource type.

#### Steps to reproduce

serializer:
```ruby
class CommentSerializer < ActiveModel::Serializer
  # ....
  belongs_to :commentable # post, image etc.
end
```

request:
`/comments?include=commentable`

expected:
```js
//...
"relationships": {
  "commentable": {
    "data": {
      "id": "1",
      "type": "posts"
    }
  }
}
//...
```

result:
```js
//...
"relationships": {
  "commentable": {
    "data": {
      "id": "1",
      "type": "commentables"
    }
  }
}
//...
```

#### Environment

ActiveModelSerializers Version, after this: #1857

### PR DESCRIPTION
**Pull request by bf4**
Closes #2160

Closes #2125

- Fix polymorphic belongs_to tests; passes on v0.10.5, fails on v0.10.6
- Fix JSON:API polymorphic type regression from v0.10.5
- Fix JSON:API: for_type_and_id should always inflect_type
    ```
    Should Serializer._type ever be inflected?
    Right now, it won't be, but association.serializer._type will be inflected.

    That's the current behavior.
     ```

Related: https://github.com/rails-api/active_model_serializers/pull/2140

### CODE REVIEW

File: lib/active_model_serializers/adapter/json_api/relationship.rb [hunk 1]
```diff
@@ -43,10 +43,16 @@ def data_for(association)
...
-          if association.belongs_to? &&
-              parent_serializer.object.respond_to?(association.reflection.foreign_key)
+          if belongs_to_id_on_self?(association)
             id = parent_serializer.read_attribute_for_serialization(association.reflection.foreign_key)
-            type = association.reflection.type.to_s
+            type =
+              if association.polymorphic?
+                # We can't infer resource type for polymorphic relationships from the serializer.
+                # We can ONLY know a polymorphic resource type by inspecting each resource.
+                association.lazy_association.serializer.json_key
```
Comment (bf4) [inline lib/active_model_serializers/adapter/json_api/relationship.rb]: cc @furkanayhan  @andyhite @rmachielse  @burmashave  @Rio517 @MidnightWonderer @cassidycodes

File: lib/active_model_serializers/adapter/json_api/resource_identifier.rb [hunk 2]
```diff
@@ -2,34 +2,35 @@ module ActiveModelSerializers
...
-            raw_type
-          end
+        def self.type_for(serializer, serializer_type = nil, transform_options = {})
+          raw_type = serializer_type ? serializer_type : raw_type_from_serializer_object(serializer.object)
           JsonApi.send(:transform_key_casing!, raw_type, transform_options)
         end
 
         def self.for_type_with_id(type, id, options)
           return nil if id.blank?
+          type = inflect_type(type)
```
Comment (bf4) [inline lib/active_model_serializers/adapter/json_api/resource_identifier.rb]: Fixes #2125

File: test/adapter/polymorphic_test.rb [hunk 3]
```diff
@@ -165,6 +165,53 @@ def test_json_api_serialization
 
           assert_equal(expected, serialization(@picture, :json_api))
         end
+
+        def test_json_api_serialization_with_polymorphic_belongs_to
```
Comment (bf4) [inline test/adapter/polymorphic_test.rb]: I added this test and ran it against the v0.10.5 tag and it passed. I then worked on 0-10-stable until it passed again

File: test/fixtures/active_record.rb [hunk 4]
```diff
@@ -89,7 +89,7 @@ class ObjectTag < ActiveRecord::Base
 end
 class PolymorphicObjectTagSerializer < ActiveModel::Serializer
   attributes :id
-  has_many :taggable, serializer: PolymorphicSimpleSerializer, polymorphic: true
+  belongs_to :taggable, serializer: PolymorphicSimpleSerializer, polymorphic: true
```
Comment (bf4) [inline test/fixtures/active_record.rb]: Not sure why the belongs_to relationships was specified with a has_many serializer method here and in the PolymorphicBelongsToSerializer below.  But this change surfaces the bug reported in #2160

**Comment by NullVoxPopuli** [comment]
LGTM :+1:
