### PR TITLE
Rendering array objects that doesn't have serializers

### LINKED ISSUE #877: [0.10.0rc1] `has_many` doesn't work without serializer defined on association
I have this serializer:

```ruby
class BrandSerializer < ActiveModel::Serializer
  attributes ...

  ...
  has_many :style_configurations
...
end
```

`style_configurations` doesn't have an AMS defined, it's just using the standard rails json response.  Under 0.9x this works fine, but on today's new RC, I get this:

```ruby
     NoMethodError:
       undefined method `new' for nil:NilClass
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/array_serializer.rb:17:in `block in initialize'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `map'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `map'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/array_serializer.rb:12:in `initialize'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer.rb:215:in `new'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer.rb:215:in `block in each_association'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer.rb:208:in `each'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer.rb:208:in `each_association'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/adapter/json.rb:17:in `serializable_hash'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/adapter.rb:23:in `as_json'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:34:in `encode'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:21:in `encode'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
     # /Users/jaiken/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc1/lib/action_controller/serialization.rb:49:in `block (2 levels) in <module:Serialization>'
```

### PR DESCRIPTION
**Pull request by joaomdmoura**
As reported on #772 and #945.
There was a crash when rendering arrays that don't consist of "serializables" classes.
This PR is a first implementation to quickly fix it.

**P.S.** It won't fix #877 yet. 
**P.S.** #954 will need to be updated based on this once merged, around [here](https://github.com/rails-api/active_model_serializers/pull/954/files#diff-07e5a5aaa325f8dc2bcf944d12f0db83R32)

### CODE REVIEW

**Comment by bf4** [comment]
ref: https://github.com/rails-api/active_model_serializers/pull/955#issuecomment-113871604

and a fix I wrote that works differently at, perhaps, the correct level?

https://github.com/rails-api/active_model_serializers/commit/56a7bd1b6dd9f083b0f3a9d6d24e9dc85efbffac

```diff
# https://github.com/rails-api/active_model_serializers/blob/56a7bd1b6dd9f083b0f3a9d6d24e9dc85efbffac/lib/active_model/serializer.rb
    def each_association(&block)
      self.class._associations.dup.each do |name, association_options|
        next unless object
        association_value = send(name)

        serializer_class = ActiveModel::Serializer.serializer_for(association_value, association_options)

         if serializer_class
-          serializer = serializer_class.new(
-            association_value,
-            options.except(:serializer).merge(serializer_from_options(association_options))
-          )
+          begin
+            serializer = serializer_class.new(
+              association_value,
+              options.except(:serializer).merge(serializer_from_options(association_options))
+            )
+          rescue NoMethodError
+            # 1. Failure to serialize an element in a collection, e.g. [ {hi: "Steve" } ] will fail
+            #    with NoMethodError when the ArraySerializer finds no serializer for the hash { hi: "Steve" },
+            #    and tries to call new on that nil.
+            # 2. Convert association_value to hash using implicit as_json
+            # 3. Set as virtual value (serializer is nil)
+            # 4. Consider warning when this happens
+            virtual_value = association_value
+            virtual_value = virtual_value.as_json if virtual_value.respond_to?(:as_json)
+            association_options[:association_options][:virtual_value] = virtual_value
+          end
```

**Comment by joaomdmoura** [comment]
@bf4, indeed a better solution, tried to backport it, but it didn't fixed the problem.

**Comment by bf4** [comment]
@joaomdmoura Yeah, looking at that now, was going to make a PR to your branch

**Comment by joaomdmoura** [comment]
@bf4 tks! I was working on it too, but no worries :smile: make yourself comfortable just let me know if you need help or anything.

**Comment by bf4** [comment]
they're closely related, but have somewhat different paths, both triggered by serializable_hash, but no common place that's called, ugh. I think I'm trying to do too much at once by combining those tests... gonna make the PR just for discussion

**Comment by bf4** [comment]
So, I think I got it figured out in that PR.  Basically, the special case can be boiled down to `ActiveModel::Serializer.serializer_for(object)` returning an `ActiveModel::Serializer.config.array_serializer` that has elements that have no serializer i.e. 

```ruby
object.any? {|elem| ActiveModel::Serializer.serializer_for(object).nil? }
```

**Comment by bf4** [comment]
So, I'm thinking maybe the solution should be in serializer_for rather than in ArraySerializer, but I'm not sure how to efficiently do that without essentially iterating over all the elements twice.

File: lib/active_model/serializer/array_serializer.rb [hunk 1]
```diff
@@ -1,10 +1,11 @@
 module ActiveModel
   class Serializer
     class ArraySerializer
+      NoSerializerError = Class.new(StandardError)
       include Enumerable
       delegate :each, to: :@objects
 
-      attr_reader :meta, :meta_key
+      attr_reader :meta, :meta_key, :objects
```
Comment (bf4) [inline lib/active_model/serializer/array_serializer.rb]: Do you want to keep `objects` reader around? It's no longer used. I could see an argument that it's a private interface.

Comment (joaomdmoura) [inline lib/active_model/serializer/array_serializer.rb]: No, indeed, there is no reason to keep it

File: lib/active_model/serializer/array_serializer.rb [hunk 2]
```diff
@@ -13,7 +14,12 @@ def initialize(objects, options = {})
             :serializer,
             ActiveModel::Serializer.serializer_for(object)
           )
-          serializer_class.new(object, options.except(:serializer))
+
+          if serializer_class.nil?
+            fail NoSerializerError, "No serializer found for object: #{object.inspect}"
+          else
+            serializer_class.new(object, options.except(:serializer))
+          end
```
Comment (bf4) [inline lib/active_model/serializer/array_serializer.rb]: What do you think about having serializer_for return nil for if any elements don't have an associated serializer?  That would maintain current PR behavior, I think, might make more sense SRP-wise, but might be a performance hit.

Should we add a test for a collection or association that contains an element with a known serializer and another with a nil serializer class?  I'm really not sure how to handle that in AMS without more complexity.  I'd rather push that back to the end user, but that could be laziness.

Comment (joaomdmoura) [inline lib/active_model/serializer/array_serializer.rb]: We would need to update this PR if we change this behaviour at ```serializer_for```.

I think it's an edge-case. I haven't heard about ppl using AMS to renders arrays that mix serializable and non-serializable objects yet, so let's not worry about it for now :smile:

Comment (bf4) [inline lib/active_model/serializer/array_serializer.rb]: winning

File: lib/action_controller/serialization.rb [hunk 3]
```diff
@@ -39,17 +39,18 @@ def use_adapter?
...
 
-          # omg hax
-          object = serializer.new(resource, @_serializer_opts)
-          adapter = ActiveModel::Serializer::Adapter.create(object, @_adapter_opts)
-          super(adapter, options)
-        else
-          super(resource, options)
+          begin
+            serialized = serializer.new(resource, @_serializer_opts)
+          rescue ActiveModel::Serializer::ArraySerializer::NoSerializerError
```
Comment (bf4) [inline lib/action_controller/serialization.rb]: We should add some docs on building your own array serializer as described in https://github.com/rails-api/active_model_serializers#2-for-an-array-resource and the use of this exception class at some point.  Want me to make an issue?

Comment (joaomdmoura) [inline lib/action_controller/serialization.rb]: I'm on a quest to keep the readme as clean as possible, but I agree that this can be helpful for some ppl, like others details that are poping up. 
I'm thinking about start the AMS wiki (using gh wiki feature). For now, make yourself comfortable to open the issue to make sure we won't forget it while I think it trough.

Comment (bf4) [inline lib/action_controller/serialization.rb]: I like wikis, but then it's another thing to garden.  For AMS I think it could be a plus.

**Comment by bf4** [comment]
Failure are Rails 4.0 only and have to do with deep munging of json keys.  I think you can configure that with `config.action_dispatch.perform_deep_munge = false` ?

**Comment by bf4** [comment]
Submitted PR to this branch in https://github.com/joaomdmoura/active_model_serializers/pull/2

**Comment by joaomdmoura** [comment]
Great team work here folks! Tks so much @JustinAiken and @bf4
I'm merging it.
